// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cfegubcyxvurhgyposwj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNmZWd1YmN5eHZ1cmhneXBvc3dqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MTE0NTYsImV4cCI6MjA3MjM4NzQ1Nn0.kV6U5oo1mAuvb0wv42LJq7GFKMencrDgQ_Sab9CTLro";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});